services:
  redis:
    image: redis:latest
    container_name: meeting_redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - meeting_redisdata:/data

volumes:
  meeting_redisdata:
